#!/usr/bin/env python3
"""Build a training manifest from paired baseline and generated case pairs."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def main() -> int:
    root = repo_root()
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-manifest", type=Path, default=root / "PINN_Poisson" / "data" / "paired_manifest.csv")
    parser.add_argument("--case-dir", type=Path, default=root / "PINN_Poisson" / "data" / "generalization_runs")
    parser.add_argument("--config-dir", type=Path, default=root / "PINN_Poisson" / "configs" / "generalization")
    parser.add_argument("--cases", default="velocity_low,velocity_high,single_droplet,tanh_interface")
    parser.add_argument("--out", type=Path, default=root / "PINN_Poisson" / "data" / "augmented_manifest.csv")
    args = parser.parse_args()

    rows = list(csv.DictReader(args.base_manifest.open()))
    if not rows:
        raise SystemExit(f"empty base manifest: {args.base_manifest}")
    keys = list(rows[0].keys())
    required = {"label", "params", "run_steps", "sample_step", "poisson", "pressure_boundary",
                "poisson_tolerance", "exit_code", "poisson_iters", "poisson_ms_per_step",
                "total_ms_per_step", "input_plt", "target_plt", "pressure_initializer",
                "diagnostics", "stdout", "command"}
    if set(keys) != required:
        raise SystemExit(f"unexpected manifest columns in {args.base_manifest}")

    for case in [text.strip() for text in args.cases.split(",") if text.strip()]:
        pre = args.case_dir / case / "pairs" / "pre_poisson" / "3D000000001.plt"
        post = args.case_dir / case / "pairs" / "post_poisson" / "3D000000001.plt"
        if not pre.exists() or not post.exists():
            raise SystemExit(f"missing generated pair for case {case}: {pre} / {post}")
        params = args.config_dir / f"{case}.in"
        rows.append({
            "label": f"aug_{case}_step1",
            "params": str(params),
            "run_steps": 1,
            "sample_step": 1,
            "poisson": "onepass",
            "pressure_boundary": "fused",
            "poisson_tolerance": 1.0e-3,
            "exit_code": 0,
            "poisson_iters": "",
            "poisson_ms_per_step": "",
            "total_ms_per_step": "",
            "input_plt": str(pre),
            "target_plt": str(post),
            "pressure_initializer": "",
            "diagnostics": "",
            "stdout": "",
            "command": "generated by build_augmented_manifest.py",
        })

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(rows)
    print(f"wrote {args.out} rows={len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
